### ISSUE TITLE
Improvement: reading configuration from google-services.json

### ISSUE THREAD

**Issue by AppWerft** [hansemannn/titanium-firebase-core#11]
Here is the code: https://github.com/AppWerft/Ti.Firebase/blob/master/android/src/ti/firebase/FirebaseModule.java

**Comment by hansemannn** [comment]
Feel free to submit a PR and test-case for this!

**Comment by m1ga** [comment]
I have a working PR for this. It will use the `file` parameter like the iOS version. It will read the given filename out of the /app/assets/android/ folder:
`fc.configure({file: "gs.json"});` will import `/app/assets/android/gs.json`

Which firebase version should I use? I've tested it with 11.0.4 since FCM is still using this and ti.playservices

**Comment by hansemannn** [comment]
Yep, 11.0.4 would be great! Let me know and I'll review the change.

**Comment by m1ga** [comment]
https://github.com/hansemannn/titanium-firebase-core/pull/16
Ready to test. I've kept the debug-log to show the actual parameters when you set them by hand or pass the file parameter. Might be handy when you debug

**Comment by hansemannn** [comment]
Thanks @m1ga !
